// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6_agraviet.Models;

namespace mission6_agraviet.Migrations
{
    [DbContext(typeof(MovieSubmissionContext))]
    [Migration("20230203174310_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission6_agraviet.Models.MovieSubmission", b =>
                {
                    b.Property<int>("submissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("submissionId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            submissionId = 1,
                            category = "Action",
                            director = "Joss Whedon",
                            edited = false,
                            lentTo = "NA",
                            notes = "mid movie",
                            rating = "PG-13",
                            title = "The Avengers",
                            year = 2012
                        },
                        new
                        {
                            submissionId = 2,
                            category = "Action",
                            director = "Tim Burton",
                            edited = false,
                            lentTo = "NA",
                            notes = "better movie",
                            rating = "PG-13",
                            title = "Batman",
                            year = 1998
                        },
                        new
                        {
                            submissionId = 3,
                            category = "Comedy",
                            director = "Jonathan Lynn",
                            edited = false,
                            lentTo = "NA",
                            notes = "never actually seen this movie",
                            rating = "PG",
                            title = "Clue",
                            year = 1985
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
