// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6_agraviet.Models;

namespace mission6_agraviet.Migrations
{
    [DbContext(typeof(MovieSubmissionContext))]
    partial class MovieSubmissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission6_agraviet.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Misc"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "TV"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "VHS"
                        });
                });

            modelBuilder.Entity("mission6_agraviet.Models.MovieSubmission", b =>
                {
                    b.Property<int>("submissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("submissionId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            submissionId = 1,
                            CategoryId = 1,
                            director = "Joss Whedon",
                            edited = false,
                            lentTo = "NA",
                            notes = "mid movie",
                            rating = "PG-13",
                            title = "The Avengers",
                            year = 2012
                        },
                        new
                        {
                            submissionId = 2,
                            CategoryId = 1,
                            director = "Tim Burton",
                            edited = false,
                            lentTo = "NA",
                            notes = "better movie",
                            rating = "PG-13",
                            title = "Batman",
                            year = 1998
                        },
                        new
                        {
                            submissionId = 3,
                            CategoryId = 2,
                            director = "Jonathan Lynn",
                            edited = false,
                            lentTo = "NA",
                            notes = "never actually seen this movie",
                            rating = "PG",
                            title = "Clue",
                            year = 1985
                        });
                });

            modelBuilder.Entity("mission6_agraviet.Models.MovieSubmission", b =>
                {
                    b.HasOne("mission6_agraviet.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
